language: android
#- echo yes | android update sdk -a -t tools,platform-tools,extra-android-support,extra-android-m2repository,android-19,build-tools-19.1.0,extra-google-google_play_services,extra-google-m2repository --force --no-ui
android:
   components:
   - tools
   - platform-tools
   - android-19
   - build-tools-20.0.0
   - extra
jdk: oraclejdk7

before_install:
  # required libs for android build tools
  - sudo apt-get update
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch