language: android
android:
   licenses:
   - 'android-sdk-preview-license-.+'
   - 'android-sdk-license-.+'
   - 'google-gdk-license-.+'
   components:
   - tools
   - platform-tools
   - android-26
   - build-tools-26.0.2
   - extra
   - extra-google-google_play_services
   - extra-google-m2repository
   - extra-android-m2repository
jdk: oraclejdk8

before_install:
  - chmod +x gradlew
  - ./gradlew build check