language: android
android:
   components:
   - tools
   - platform-tools
   - android-26
   - build-tools-26.0.2
   - extra
jdk: oraclejdk8

before_install:
  - chmod +x gradlew
  # required libs for android build tools
  - sudo apt-get update